after-login-command = []

after-startup-command = []

start-at-login = true

exec-on-workspace-change = ['/bin/bash', '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE PREV_WORKSPACE=$AEROSPACE_PREV_WORKSPACE'
]

on-focus-changed = ['move-mouse window-lazy-center']

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

key-mapping.preset = 'qwerty'

[workspace-to-monitor-force-assignment]
3 = 'Built-in Retina Display'
4 = 'Built-in Retina Display'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[gaps]
inner.horizontal = [{ monitor.'LC32G7xT' = 5 }, { monitor.main = 5 }, 5]
inner.vertical = [{ monitor.'LC32G7xT' = 5}, { monitor.main = 5 }, 5]
outer.left = [{ monitor.'LC32G7xT' = 5 }, { monitor.main = 5 }, 5]
outer.right = [{ monitor.'LC32G7xT' = 5 }, { monitor.main = 5 }, 5]
outer.bottom = [{ monitor.'LC32G7xT' = 5 }, { monitor.main = 5 }, 5]
outer.top = [{ monitor.'LC32G7xT' = 40 }, { monitor.'Built-in Retina Display' = 10 }, 20]



[[on-window-detected]]
if.app-name-regex-substring = 'Arc'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-name-regex-substring = 'Google Chrome'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-name-regex-substring = 'Brave'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-name-regex-substring = 'zen'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-name-regex-substring = 'ghostty'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-name-regex-substring = 'RunJs'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-name-regex-substring = 'cursor'
run = ['layout tiling','move-node-to-workspace 2']

[[on-window-detected]]
if.app-name-regex-substring = 'code'
run = ['layout tiling','move-node-to-workspace 2']

[[on-window-detected]]
if.app-name-regex-substring = 'iina'
run = ['layout floating','move-node-to-workspace 4']

[[on-window-detected]]
if.app-name-regex-substring = 'bartender'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'finder'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'excalidraw'
run = 'move-node-to-workspace 3'

[[on-window-detected]]
if.app-name-regex-substring = 'spark'
run = 'move-node-to-workspace 3'

[[on-window-detected]]
if.app-name-regex-substring = 'goodnotes'
run = 'move-node-to-workspace 4'

[[on-window-detected]]
if.app-name-regex-substring = 'obsidian'
run = 'move-node-to-workspace 4'

[[on-window-detected]]
if.app-name-regex-substring = 'discord'
run = 'move-node-to-workspace 7'

[[on-window-detected]]
if.app-name-regex-substring = 'Telegram'
run = 'move-node-to-workspace 7'

[[on-window-detected]]
if.app-name-regex-substring = 'finder'
run = 'move-node-to-workspace 8'

[[on-window-detected]]
if.app-name-regex-substring = 'spotify'
run = 'move-node-to-workspace 9'

[mode.main.binding]
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

alt-h = 'focus --boundaries all-monitors-outer-frame left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus --boundaries all-monitors-outer-frame right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'

alt-shift-f = 'fullscreen'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'
alt-shift-semicolon = 'mode service'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main']
f = ['layout floating tiling', 'mode main']
backspace = ['close-all-windows-but-current', 'mode main']

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']
