git:
  pagers:
    - pager: delta --dark --paging=never --line-numbers
      colorArg: always
os:
  editPreset: nvim-remote

customCommands:
  - key: "o"
    context: "files"
    command: "nvim -- {{ .SelectedFile.Name | quote }}"
    description: "Open in nvim"
    output: terminal
