#!/usr/bin/env lua

os.execute(
	"[ ! -f $HOME/Library/Fonts/sketchybar-app-font.ttf ] && curl -L https://github.com/kvndrsslr/sketchybar-app-font/releases/download/v2.0.28/sketchybar-app-font.ttf -o $HOME/Library/Fonts/sketchybar-app-font.ttf "
)
os.execute(
	"[ ! -d $HOME/.local/share/sketchybar_lua/ ] && (git clone https://github.com/FelixKratz/SbarLua.git /tmp/SbarLua && cd /tmp/SbarLua/ && make install && rm -rf /tmp/SbarLua/)"
)

-- Load the sketchybar-package and prepare the helper binaries
require("helpers")
require("init")
