name: Dotfiles CI

on: [push, pull_request]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install shellcheck
        run: sudo apt-get install -y shellcheck

      - name: Shellcheck all scripts
        run: |
          shellcheck ./run
          find ./runs_MacOS -type f -executable -exec shellcheck {} +
          find ./.local/scripts -type f -executable -exec shellcheck {} +

  full-install-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run full installation
        run: ./run
        timeout-minutes: 90

      - name: Verify key installations
        run: |
          echo "=== Verifying installations ==="
          command -v nvim && nvim --version || echo "❌ neovim not found"
          command -v git && git --version || echo "❌ git not found"
          command -v gh && gh --version || echo "❌ gh not found"
          command -v tmux && tmux -V || echo "❌ tmux not found"
          command -v rg && rg --version || echo "❌ ripgrep not found"
          command -v lazygit && lazygit --version || echo "❌ lazygit not found"
          command -v btop && btop --version || echo "❌ btop not found"
