name: Dotfiles CI

on: [push, pull_request]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install shellcheck
        run: sudo apt-get install -y shellcheck

      - name: Shellcheck all scripts
        run: |
          shellcheck ./run
          find ./runs_MacOS -type f -executable -exec shellcheck {} +
          find ./.local/scripts -type f -executable -exec shellcheck {} +

  syntax-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Bash syntax check
        run: |
          bash -n ./run
          for script in ./runs_MacOS/*; do
            [ -f "$script" ] && bash -n "$script"
          done
